/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biblioteca.GUI;

import SqlOps.ConexionSql;
import domain.Credenciales;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Inicio extends javax.swing.JFrame {

    int xMouse, yMouse;
    static String DbUser = null;
    static String DbPass = null;
    
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Head = new javax.swing.JPanel();
        BtnSalir = new javax.swing.JPanel();
        Salir = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usuariofield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PassTxt = new javax.swing.JPasswordField();
        BtnInicio = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Mostrar = new javax.swing.JCheckBox();
        ErrorUser = new javax.swing.JLabel();
        ErrorPass = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Biblioteca/GUI/imagees/Logo.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 300, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Biblioteca/GUI/imagees/Wall.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, 300, 750));

        Head.setBackground(new java.awt.Color(255, 255, 255));
        Head.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeadMouseDragged(evt);
            }
        });
        Head.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeadMousePressed(evt);
            }
        });

        BtnSalir.setBackground(new java.awt.Color(255, 255, 255));

        Salir.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        Salir.setForeground(new java.awt.Color(0, 0, 0));
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir.setText("X");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnSalirLayout = new javax.swing.GroupLayout(BtnSalir);
        BtnSalir.setLayout(BtnSalirLayout);
        BtnSalirLayout.setHorizontalGroup(
            BtnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );
        BtnSalirLayout.setVerticalGroup(
            BtnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Salir, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 995, Short.MAX_VALUE))
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(Head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 60));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Biblioteca/GUI/imagees/favicon.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, 90));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("dbLib");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Iniciar Sesión");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Usuario");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        usuariofield.setBackground(new java.awt.Color(255, 255, 255));
        usuariofield.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        usuariofield.setForeground(new java.awt.Color(204, 204, 204));
        usuariofield.setText("Ingrese su usuario");
        usuariofield.setBorder(null);
        usuariofield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                usuariofieldMousePressed(evt);
            }
        });
        usuariofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariofieldActionPerformed(evt);
            }
        });
        jPanel1.add(usuariofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 640, 40));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Contraseña");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        PassTxt.setBackground(new java.awt.Color(255, 255, 255));
        PassTxt.setText("********");
        PassTxt.setBorder(null);
        PassTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PassTxtMousePressed(evt);
            }
        });
        PassTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassTxtActionPerformed(evt);
            }
        });
        jPanel1.add(PassTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 640, 40));

        BtnInicio.setBackground(new java.awt.Color(0, 100, 150));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("INGRESAR");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnInicioLayout = new javax.swing.GroupLayout(BtnInicio);
        BtnInicio.setLayout(BtnInicioLayout);
        BtnInicioLayout.setHorizontalGroup(
            BtnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        BtnInicioLayout.setVerticalGroup(
            BtnInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.add(BtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 160, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 640, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 640, -1));

        Mostrar.setBackground(new java.awt.Color(255, 255, 255));
        Mostrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        Mostrar.setForeground(new java.awt.Color(0, 0, 0));
        Mostrar.setText("Mostrar");
        Mostrar.setBorder(null);
        Mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarActionPerformed(evt);
            }
        });
        jPanel1.add(Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, -1, -1));

        ErrorUser.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(ErrorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 640, 40));
        jPanel1.add(ErrorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 540, 30));

        Estado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Estado.setForeground(new java.awt.Color(250, 250, 250));
        Estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Estado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuariofieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariofieldMousePressed
        if (usuariofield.getText().equals("Ingrese su usuario")) {
            usuariofield.setText("");
            usuariofield.setForeground(Color.black);
        }
        if (String.valueOf(PassTxt.getPassword()).isEmpty()) {
            PassTxt.setText("********");
            PassTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_usuariofieldMousePressed

    private void PassTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassTxtActionPerformed

    private void PassTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassTxtMousePressed
        if (String.valueOf(PassTxt.getPassword()).equals("********")) {
            PassTxt.setText("");
            PassTxt.setForeground(Color.black);
        }

        if (usuariofield.getText().isEmpty()) {
            usuariofield.setText("Ingrese su usuario");
            usuariofield.setForeground(Color.gray);
        }
    }//GEN-LAST:event_PassTxtMousePressed

    private void HeadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeadMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();

    }//GEN-LAST:event_HeadMousePressed

    private void HeadMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeadMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeadMouseDragged

    private void SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirMouseClicked

    private void SalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseEntered
        BtnSalir.setBackground(Color.red);
        Salir.setForeground(Color.white);
    }//GEN-LAST:event_SalirMouseEntered

    private void SalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMouseExited
        BtnSalir.setBackground(Color.white);
        Salir.setForeground(Color.black);
    }//GEN-LAST:event_SalirMouseExited

    private void MostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarActionPerformed
        if (Mostrar.isSelected()) {
            PassTxt.setEchoChar((char) 0);
        } else {
            PassTxt.setEchoChar('*');
            PassTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_MostrarActionPerformed

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        BtnInicio.setBackground(new Color(5, 124, 226));
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        BtnInicio.setBackground(new Color(0, 100, 150));
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        String usuario = usuariofield.getText();
        String Contra = PassTxt.getText();

        if (usuario.equals("") || usuario.equals("Ingrese su usuario")) {
            ErrorUser.setText("Este campo no puede quedar vacio");
            ErrorUser.setForeground(Color.red);
        } else {
            ErrorUser.setText("");
        }

        if (Contra.equals("") || Contra.equals("********")) {
            ErrorPass.setText("Este campo no puede quedar vacio");
            ErrorPass.setForeground(Color.red);
        } else {
            ErrorPass.setText("");
        }
        if ((!usuario.equals("") || !usuario.equals("Ingrese su usuario")) && (!Contra.equals("") || !Contra.equals("********"))) {
            //Credenciales validacion = new Credenciales();
            //AISLADO TEMPORALMENTE, NECESITA CORRECCION DE MÉTODO
            if(Credenciales.buscarEstudiante(usuario, Contra, DbUser, DbPass)) {
                Estado.setText("Acceso autorizado Alumno");
                Estado.setForeground(Color.green);
                dispose();
                Menu.menu(null);
            } 
            else if(Credenciales.buscarProfesor(usuario, Contra, DbUser, DbPass)) {
                Estado.setText("Acceso autorizado Profesor");
                Estado.setForeground(Color.green);
                dispose();
                Menu.menu(null);
            }
            else if(Credenciales.buscarAdmin(usuario, Contra, DbUser, DbPass)) {
                Estado.setText("Acceso autorizado Administrador");
                Estado.setForeground(Color.green);
                dispose();
                Menu.menu(null);
            }
            else {
                Estado.setText("Credenciales inválidas");
                Estado.setForeground(Color.red);
            }
        } else {
            Estado.setText("");
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void usuariofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariofieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            DbUser = JOptionPane.showInputDialog("Ingrese su usuario de la DB");
            DbPass = JOptionPane.showInputDialog("Ingrese la contraseña de la DB");
            ConexionSql.getConnection(DbUser, DbPass);
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Inicio().setVisible(true);
                }
            });
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error al conectarse con la DB: " + ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnInicio;
    private javax.swing.JPanel BtnSalir;
    private javax.swing.JLabel ErrorPass;
    private javax.swing.JLabel ErrorUser;
    private javax.swing.JLabel Estado;
    private javax.swing.JPanel Head;
    private javax.swing.JCheckBox Mostrar;
    private javax.swing.JPasswordField PassTxt;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField usuariofield;
    // End of variables declaration//GEN-END:variables
}
