/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Biblioteca.GUI;

import java.awt.Color;

/**
 *
 * @author HP
 */
public class Pestañas extends javax.swing.JPanel {

    /**
     * Creates new form Pestañas
     */
    public Pestañas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Rol = new javax.swing.ButtonGroup();
        ROl = new javax.swing.ButtonGroup();
        ROL = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        identificador = new javax.swing.JLabel();
        Carrera = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        Area = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        BtnReg = new javax.swing.JPanel();
        Registrar = new javax.swing.JLabel();
        MaestroCheck = new javax.swing.JCheckBox();
        AlumnoCheck = new javax.swing.JCheckBox();
        Err1 = new javax.swing.JLabel();
        Err2 = new javax.swing.JLabel();
        Err3 = new javax.swing.JLabel();
        Err4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        mister = new javax.swing.JCheckBox();
        Estudi = new javax.swing.JCheckBox();
        IdMod = new javax.swing.JLabel();
        IdField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        CarrMod = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Master = new javax.swing.JCheckBox();
        Student = new javax.swing.JCheckBox();
        IdElim = new javax.swing.JLabel();
        Ident = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        Err5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(690, 750));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Biblioteca/GUI/imagees/285641_id_user_icon.png"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro de nuevo usuario");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        identificador.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        identificador.setForeground(new java.awt.Color(0, 0, 0));
        identificador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        identificador.setText("ID:");
        jPanel5.add(identificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        Carrera.setBackground(new java.awt.Color(204, 204, 204));
        Carrera.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Carrera.setForeground(new java.awt.Color(0, 0, 0));
        Carrera.setBorder(null);
        jPanel5.add(Carrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 440, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        ID.setBackground(new java.awt.Color(204, 204, 204));
        ID.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ID.setForeground(new java.awt.Color(0, 0, 0));
        ID.setBorder(null);
        jPanel5.add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 440, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Apellido:");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        Nombre.setBackground(new java.awt.Color(204, 204, 204));
        Nombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Nombre.setForeground(new java.awt.Color(0, 0, 0));
        Nombre.setBorder(null);
        jPanel5.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 440, 30));

        Area.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Area.setForeground(new java.awt.Color(0, 0, 0));
        Area.setText("Carrera:");
        jPanel5.add(Area, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        Apellido.setBackground(new java.awt.Color(204, 204, 204));
        Apellido.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Apellido.setForeground(new java.awt.Color(0, 0, 0));
        Apellido.setBorder(null);
        jPanel5.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 440, 30));

        BtnReg.setBackground(new java.awt.Color(0, 100, 150));

        Registrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Registrar.setForeground(new java.awt.Color(255, 255, 255));
        Registrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registrar.setText("Registrar");
        Registrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RegistrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnRegLayout = new javax.swing.GroupLayout(BtnReg);
        BtnReg.setLayout(BtnRegLayout);
        BtnRegLayout.setHorizontalGroup(
            BtnRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        BtnRegLayout.setVerticalGroup(
            BtnRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Registrar, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel5.add(BtnReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 550, 130, 50));

        MaestroCheck.setBackground(new java.awt.Color(255, 255, 255));
        Rol.add(MaestroCheck);
        MaestroCheck.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        MaestroCheck.setForeground(new java.awt.Color(0, 0, 0));
        MaestroCheck.setText("Maestro");
        MaestroCheck.setBorder(null);
        MaestroCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaestroCheckActionPerformed(evt);
            }
        });
        jPanel5.add(MaestroCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        AlumnoCheck.setBackground(new java.awt.Color(255, 255, 255));
        Rol.add(AlumnoCheck);
        AlumnoCheck.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        AlumnoCheck.setForeground(new java.awt.Color(0, 0, 0));
        AlumnoCheck.setText("Alumno");
        AlumnoCheck.setBorder(null);
        AlumnoCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlumnoCheckActionPerformed(evt);
            }
        });
        jPanel5.add(AlumnoCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));
        jPanel5.add(Err1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 440, -1));
        jPanel5.add(Err2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 440, -1));
        jPanel5.add(Err3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 440, -1));
        jPanel5.add(Err4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 440, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Crear", jPanel1);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Biblioteca/GUI/imagees/editar.png"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Modificar");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        mister.setBackground(new java.awt.Color(255, 255, 255));
        ROl.add(mister);
        mister.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        mister.setForeground(new java.awt.Color(0, 0, 0));
        mister.setText("Maestro");
        mister.setBorder(null);
        mister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misterActionPerformed(evt);
            }
        });
        jPanel6.add(mister, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        Estudi.setBackground(new java.awt.Color(255, 255, 255));
        ROl.add(Estudi);
        Estudi.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Estudi.setForeground(new java.awt.Color(0, 0, 0));
        Estudi.setText("Alumno");
        Estudi.setBorder(null);
        Estudi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstudiActionPerformed(evt);
            }
        });
        jPanel6.add(Estudi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        IdMod.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        IdMod.setForeground(new java.awt.Color(0, 0, 0));
        IdMod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IdMod.setText("ID:");
        jPanel6.add(IdMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        IdField.setBackground(new java.awt.Color(204, 204, 204));
        IdField.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        IdField.setForeground(new java.awt.Color(0, 0, 0));
        IdField.setBorder(null);
        jPanel6.add(IdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 440, 30));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Nombre:");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(0, 0, 0));
        jTextField6.setBorder(null);
        jPanel6.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 440, 30));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Apellido:");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jTextField7.setBackground(new java.awt.Color(204, 204, 204));
        jTextField7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(0, 0, 0));
        jTextField7.setBorder(null);
        jPanel6.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 440, 30));

        CarrMod.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        CarrMod.setForeground(new java.awt.Color(0, 0, 0));
        CarrMod.setText("Carrera:");
        jPanel6.add(CarrMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(0, 0, 0));
        jTextField8.setBorder(null);
        jPanel6.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 440, 30));

        jPanel7.setBackground(new java.awt.Color(0, 100, 150));

        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Modificar");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 630, 120, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Password:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setBorder(null);
        jPanel6.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 440, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Modificar", jPanel3);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Biblioteca/GUI/imagees/9004743_trash_delete_bin_remove_icon (2).png"))); // NOI18N
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 29, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Eliminar");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 53, -1, -1));

        Master.setBackground(new java.awt.Color(255, 255, 255));
        ROL.add(Master);
        Master.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Master.setForeground(new java.awt.Color(0, 0, 0));
        Master.setText("Maestro");
        Master.setBorder(null);
        Master.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasterActionPerformed(evt);
            }
        });
        jPanel8.add(Master, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        Student.setBackground(new java.awt.Color(255, 255, 255));
        ROL.add(Student);
        Student.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        Student.setForeground(new java.awt.Color(0, 0, 0));
        Student.setText("Alumno");
        Student.setBorder(null);
        Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentActionPerformed(evt);
            }
        });
        jPanel8.add(Student, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        IdElim.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        IdElim.setForeground(new java.awt.Color(0, 0, 0));
        IdElim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IdElim.setText("ID:");
        jPanel8.add(IdElim, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        Ident.setBackground(new java.awt.Color(204, 204, 204));
        Ident.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Ident.setForeground(new java.awt.Color(0, 0, 0));
        Ident.setBorder(null);
        jPanel8.add(Ident, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 440, 30));

        jPanel9.setBackground(new java.awt.Color(0, 100, 150));

        jLabel17.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Eliminar");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 529, -1, -1));
        jPanel8.add(Err5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 440, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Eliminar", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseEntered
        BtnReg.setBackground(new Color(5, 124, 226));
    }//GEN-LAST:event_RegistrarMouseEntered

    private void RegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseExited
        BtnReg.setBackground(new Color(0, 100, 150));
    }//GEN-LAST:event_RegistrarMouseExited

    private void RegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegistrarMouseClicked
        String nombre= Nombre.getText();
        String id= ID.getText();
        String apellido= Apellido.getText();
        String carrera= Carrera.getText();
        
        if (id.isEmpty()){
            Err1.setForeground(Color.red);
            Err1.setText("Este campo no puede quedar vacío.");
        }
        else{
            Err1.setForeground(Color.white);
            Err1.setText("");
        }
        
        if (nombre.isEmpty()){
            Err2.setForeground(Color.red);
            Err2.setText("Este campo no puede quedar vacío.");
        }
        else{
            Err2.setForeground(Color.white);
            Err2.setText("");
        }
        
        if (apellido.isEmpty()){
            Err3.setForeground(Color.red);
            Err3.setText ("Este campo es obligatorio");
        }
        else{
            Err3.setText("");
        }
        if (carrera.isEmpty()){
            Err4.setForeground(Color.red);
            Err4.setText("Este campo es obligatorio");
        }
        else
        {
            Err4.setText("");
        }
        
        
    }//GEN-LAST:event_RegistrarMouseClicked

    private void MaestroCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaestroCheckActionPerformed
        if(MaestroCheck.isSelected()){
            identificador.setText("DUI: ");
            Area.setText("Facultad: ");
        }
       
    }//GEN-LAST:event_MaestroCheckActionPerformed

    private void AlumnoCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlumnoCheckActionPerformed
         if (AlumnoCheck.isSelected()){
            identificador.setText("Carnet: ");
            Area.setText("Carrera: ");
        }
    }//GEN-LAST:event_AlumnoCheckActionPerformed

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        String ident=Ident.getText();
        
        if(ident.isEmpty()){
            Err5.setForeground(Color.RED);
            Err5.setText("Este campo es obligatorio.");
        }
        else{
            Err5.setText("");
        }
    }//GEN-LAST:event_jLabel17MouseClicked

    private void MasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasterActionPerformed
        if(Master.isSelected()){
            IdElim.setText("DUI: ");
        }
    }//GEN-LAST:event_MasterActionPerformed

    private void StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentActionPerformed
        if(Student.isSelected()){
            IdElim.setText("Carnet: ");
        }
    }//GEN-LAST:event_StudentActionPerformed

    private void misterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misterActionPerformed
        if(mister.isSelected()){
            IdMod.setText("DUI: ");
            CarrMod.setText("Facultad");
        }
        
        IdField.setEditable(false);
        IdField.setEnabled(false);
        
    }//GEN-LAST:event_misterActionPerformed

    private void EstudiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstudiActionPerformed
        if (Estudi.isSelected()){
            IdMod.setText("Carnet: ");
            CarrMod.setText("Carrera: ");
        }
        
        IdField.setEditable(false);
        IdField.setEnabled(false);
        
    }//GEN-LAST:event_EstudiActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AlumnoCheck;
    private javax.swing.JTextField Apellido;
    private javax.swing.JLabel Area;
    private javax.swing.JPanel BtnReg;
    private javax.swing.JLabel CarrMod;
    private javax.swing.JTextField Carrera;
    private javax.swing.JLabel Err1;
    private javax.swing.JLabel Err2;
    private javax.swing.JLabel Err3;
    private javax.swing.JLabel Err4;
    private javax.swing.JLabel Err5;
    private javax.swing.JCheckBox Estudi;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel IdElim;
    private javax.swing.JTextField IdField;
    private javax.swing.JLabel IdMod;
    private javax.swing.JTextField Ident;
    private javax.swing.JCheckBox MaestroCheck;
    private javax.swing.JCheckBox Master;
    private javax.swing.JTextField Nombre;
    private javax.swing.ButtonGroup ROL;
    private javax.swing.ButtonGroup ROl;
    private javax.swing.JLabel Registrar;
    private javax.swing.ButtonGroup Rol;
    private javax.swing.JCheckBox Student;
    private javax.swing.JLabel identificador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JCheckBox mister;
    // End of variables declaration//GEN-END:variables
}
